# CMake generated Testfile for 
# Source directory: /home/boris/cpp-advanced-hse/asan_build/glog/glog-src
# Build directory: /home/boris/cpp-advanced-hse/asan_build/glog/glog-build
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(demangle "/home/boris/cpp-advanced-hse/asan_build/demangle_unittest")
set_tests_properties(demangle PROPERTIES  _BACKTRACE_TRIPLES "/home/boris/cpp-advanced-hse/asan_build/glog/glog-src/CMakeLists.txt;835;add_test;/home/boris/cpp-advanced-hse/asan_build/glog/glog-src/CMakeLists.txt;0;")
add_test(logging "/home/boris/cpp-advanced-hse/asan_build/logging_unittest")
set_tests_properties(logging PROPERTIES  SKIP_REGULAR_EXPRESSION "Check failed: time_ns within LogTimes::LOG_PERIOD_TOL_NS of LogTimes::LOG_PERIOD_NS" TIMEOUT "30" _BACKTRACE_TRIPLES "/home/boris/cpp-advanced-hse/asan_build/glog/glog-src/CMakeLists.txt;836;add_test;/home/boris/cpp-advanced-hse/asan_build/glog/glog-src/CMakeLists.txt;0;")
add_test(signalhandler "/home/boris/cpp-advanced-hse/asan_build/signalhandler_unittest")
set_tests_properties(signalhandler PROPERTIES  _BACKTRACE_TRIPLES "/home/boris/cpp-advanced-hse/asan_build/glog/glog-src/CMakeLists.txt;851;add_test;/home/boris/cpp-advanced-hse/asan_build/glog/glog-src/CMakeLists.txt;0;")
add_test(stacktrace "/home/boris/cpp-advanced-hse/asan_build/stacktrace_unittest")
set_tests_properties(stacktrace PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "/home/boris/cpp-advanced-hse/asan_build/glog/glog-src/CMakeLists.txt;855;add_test;/home/boris/cpp-advanced-hse/asan_build/glog/glog-src/CMakeLists.txt;0;")
add_test(stl_logging "/home/boris/cpp-advanced-hse/asan_build/stl_logging_unittest")
set_tests_properties(stl_logging PROPERTIES  _BACKTRACE_TRIPLES "/home/boris/cpp-advanced-hse/asan_build/glog/glog-src/CMakeLists.txt;859;add_test;/home/boris/cpp-advanced-hse/asan_build/glog/glog-src/CMakeLists.txt;0;")
add_test(symbolize "/home/boris/cpp-advanced-hse/asan_build/symbolize_unittest")
set_tests_properties(symbolize PROPERTIES  _BACKTRACE_TRIPLES "/home/boris/cpp-advanced-hse/asan_build/glog/glog-src/CMakeLists.txt;862;add_test;/home/boris/cpp-advanced-hse/asan_build/glog/glog-src/CMakeLists.txt;0;")
add_test(cmake_package_config_init "/usr/bin/cmake" "-DTEST_BINARY_DIR=/home/boris/cpp-advanced-hse/asan_build/glog/glog-build/test_package_config" "-DINITIAL_CACHE=/home/boris/cpp-advanced-hse/asan_build/glog/glog-build/test_package_config/glog_package_config_initial_cache.cmake" "-DCACHEVARS=set (BUILD_SHARED_LIBS OFF CACHE BOOL \"Build shared libraries\")
set (BUILD_TESTING ON CACHE BOOL \"Build the testing tree.\")
set (CMAKE_ADDR2LINE \"/usr/bin/addr2line\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_AR \"/usr/bin/ar\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_AR \"/usr/bin/ar\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_BUILD_TYPE \"ASAN\" CACHE STRING \"Choose the type of build, options are: None Debug Release RelWithDebInfo MinSizeRel ...\")
set (CMAKE_COLOR_MAKEFILE ON CACHE BOOL \"Enable/Disable color output during build.\")
set (CMAKE_CXX_COMPILER \"/usr/bin/c++\" CACHE FILEPATH \"CXX compiler\")
set (CMAKE_CXX_COMPILER \"/usr/bin/c++\" CACHE FILEPATH \"CXX compiler\")
set (CMAKE_CXX_COMPILER_AR \"/usr/bin/gcc-ar-11\" CACHE FILEPATH \"A wrapper around 'ar' adding the appropriate '--plugin' option for the GCC compiler\")
set (CMAKE_CXX_COMPILER_AR \"/usr/bin/gcc-ar-11\" CACHE FILEPATH \"A wrapper around 'ar' adding the appropriate '--plugin' option for the GCC compiler\")
set (CMAKE_CXX_COMPILER_RANLIB \"/usr/bin/gcc-ranlib-11\" CACHE FILEPATH \"A wrapper around 'ranlib' adding the appropriate '--plugin' option for the GCC compiler\")
set (CMAKE_CXX_COMPILER_RANLIB \"/usr/bin/gcc-ranlib-11\" CACHE FILEPATH \"A wrapper around 'ranlib' adding the appropriate '--plugin' option for the GCC compiler\")
set (CMAKE_CXX_FLAGS_ASAN \"-g -fsanitize=address,undefined -fno-sanitize-recover=all\" CACHE STRING \"Compiler flags in asan build\")
set (CMAKE_CXX_FLAGS_DEBUG \"-g\" CACHE STRING \"Flags used by the CXX compiler during DEBUG builds.\")
set (CMAKE_CXX_FLAGS_MINSIZEREL \"-Os -DNDEBUG\" CACHE STRING \"Flags used by the CXX compiler during MINSIZEREL builds.\")
set (CMAKE_CXX_FLAGS_MSAN \"-g -fsanitize=memory -fsanitize-recover=all\" CACHE STRING \"Compiler flags in msan build\")
set (CMAKE_CXX_FLAGS_RELEASE \"-O3 -DNDEBUG\" CACHE STRING \"Flags used by the CXX compiler during RELEASE builds.\")
set (CMAKE_CXX_FLAGS_RELWITHDEBINFO \"-O2 -g -DNDEBUG\" CACHE STRING \"Flags used by the CXX compiler during RELWITHDEBINFO builds.\")
set (CMAKE_CXX_FLAGS_TSAN \"-g -fsanitize=thread -fno-sanitize-recover=all\" CACHE STRING \"Compiler flags in tsan build\")
set (CMAKE_C_COMPILER \"/usr/bin/cc\" CACHE FILEPATH \"C compiler\")
set (CMAKE_C_COMPILER \"/usr/bin/cc\" CACHE FILEPATH \"C compiler\")
set (CMAKE_C_COMPILER_AR \"/usr/bin/gcc-ar-11\" CACHE FILEPATH \"A wrapper around 'ar' adding the appropriate '--plugin' option for the GCC compiler\")
set (CMAKE_C_COMPILER_AR \"/usr/bin/gcc-ar-11\" CACHE FILEPATH \"A wrapper around 'ar' adding the appropriate '--plugin' option for the GCC compiler\")
set (CMAKE_C_COMPILER_RANLIB \"/usr/bin/gcc-ranlib-11\" CACHE FILEPATH \"A wrapper around 'ranlib' adding the appropriate '--plugin' option for the GCC compiler\")
set (CMAKE_C_COMPILER_RANLIB \"/usr/bin/gcc-ranlib-11\" CACHE FILEPATH \"A wrapper around 'ranlib' adding the appropriate '--plugin' option for the GCC compiler\")
set (CMAKE_C_FLAGS_DEBUG \"-g\" CACHE STRING \"Flags used by the C compiler during DEBUG builds.\")
set (CMAKE_C_FLAGS_MINSIZEREL \"-Os -DNDEBUG\" CACHE STRING \"Flags used by the C compiler during MINSIZEREL builds.\")
set (CMAKE_C_FLAGS_RELEASE \"-O3 -DNDEBUG\" CACHE STRING \"Flags used by the C compiler during RELEASE builds.\")
set (CMAKE_C_FLAGS_RELWITHDEBINFO \"-O2 -g -DNDEBUG\" CACHE STRING \"Flags used by the C compiler during RELWITHDEBINFO builds.\")
set (CMAKE_DLLTOOL \"CMAKE_DLLTOOL-NOTFOUND\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_INSTALL_BINDIR \"bin\" CACHE PATH \"User executables (bin)\")
set (CMAKE_INSTALL_DATAROOTDIR \"share\" CACHE PATH \"Read-only architecture-independent data root (share)\")
set (CMAKE_INSTALL_INCLUDEDIR \"include\" CACHE PATH \"C header files (include)\")
set (CMAKE_INSTALL_LIBDIR \"lib\" CACHE PATH \"Object code libraries (lib)\")
set (CMAKE_INSTALL_LIBEXECDIR \"libexec\" CACHE PATH \"Program executables (libexec)\")
set (CMAKE_INSTALL_LOCALSTATEDIR \"var\" CACHE PATH \"Modifiable single-machine data (var)\")
set (CMAKE_INSTALL_OLDINCLUDEDIR \"/usr/include\" CACHE PATH \"C header files for non-gcc (/usr/include)\")
set (CMAKE_INSTALL_PREFIX \"/usr/local\" CACHE PATH \"Install path prefix, prepended onto install directories.\")
set (CMAKE_INSTALL_SBINDIR \"sbin\" CACHE PATH \"System admin executables (sbin)\")
set (CMAKE_INSTALL_SHAREDSTATEDIR \"com\" CACHE PATH \"Modifiable architecture-independent data (com)\")
set (CMAKE_INSTALL_SYSCONFDIR \"etc\" CACHE PATH \"Read-only single-machine data (etc)\")
set (CMAKE_LINKER \"/usr/bin/ld\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_LINKER \"/usr/bin/ld\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_MAKE_PROGRAM \"/usr/bin/gmake\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_NM \"/usr/bin/nm\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_OBJCOPY \"/usr/bin/objcopy\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_OBJDUMP \"/usr/bin/objdump\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_RANLIB \"/usr/bin/ranlib\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_RANLIB \"/usr/bin/ranlib\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_READELF \"/usr/bin/readelf\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_SKIP_INSTALL_RPATH NO CACHE BOOL \"If set, runtime paths are not added when installing shared libraries, but are added when building.\")
set (CMAKE_SKIP_RPATH NO CACHE BOOL \"If set, runtime paths are not added when using shared libraries.\")
set (CMAKE_STRIP \"/usr/bin/strip\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_VERBOSE_MAKEFILE FALSE CACHE BOOL \"If this value is on, makefiles will be generated without the .SILENT directive, and all commands_ will be echoed to the console during the make.  This is useful for debugging only. With Visual Studio IDE projects all commands_ are done without /nologo.\")
set (COVERAGE_COMMAND \"/usr/bin/gcov\" CACHE FILEPATH \"Path to the coverage program that CTest uses for performing coverage inspection\")
set (COVERAGE_EXTRA_FLAGS \"-l\" CACHE STRING \"Extra command line flags to pass to the coverage tool\")
set (CPACK_BINARY_DEB OFF CACHE BOOL \"Enable to build Debian packages\")
set (CPACK_BINARY_FREEBSD OFF CACHE BOOL \"Enable to build FreeBSD packages\")
set (CPACK_BINARY_IFW OFF CACHE BOOL \"Enable to build IFW packages\")
set (CPACK_BINARY_NSIS OFF CACHE BOOL \"Enable to build NSIS packages\")
set (CPACK_BINARY_RPM OFF CACHE BOOL \"Enable to build RPM packages\")
set (CPACK_BINARY_STGZ ON CACHE BOOL \"Enable to build STGZ packages\")
set (CPACK_BINARY_TBZ2 OFF CACHE BOOL \"Enable to build TBZ2 packages\")
set (CPACK_BINARY_TGZ ON CACHE BOOL \"Enable to build TGZ packages\")
set (CPACK_BINARY_TXZ OFF CACHE BOOL \"Enable to build TXZ packages\")
set (CPACK_BINARY_TZ ON CACHE BOOL \"Enable to build TZ packages\")
set (CPACK_SOURCE_RPM OFF CACHE BOOL \"Enable to build RPM source packages\")
set (CPACK_SOURCE_TBZ2 ON CACHE BOOL \"Enable to build TBZ2 source packages\")
set (CPACK_SOURCE_TGZ ON CACHE BOOL \"Enable to build TGZ source packages\")
set (CPACK_SOURCE_TXZ ON CACHE BOOL \"Enable to build TXZ source packages\")
set (CPACK_SOURCE_TZ ON CACHE BOOL \"Enable to build TZ source packages\")
set (CPACK_SOURCE_ZIP OFF CACHE BOOL \"Enable to build ZIP source packages\")
set (CTEST_SUBMIT_RETRY_COUNT \"3\" CACHE STRING \"How many times to retry timed-out CTest submissions.\")
set (CTEST_SUBMIT_RETRY_DELAY \"5\" CACHE STRING \"How long to wait between timed-out CTest submissions.\")
set (DART_TESTING_TIMEOUT \"1500\" CACHE STRING \"Maximum time allowed before CTest will kill the test.\")
set (ENABLE_SEMINARS OFF CACHE BOOL \"OFF\")
set (FETCHCONTENT_BASE_DIR \"/home/boris/cpp-advanced-hse/asan_build/_deps\" CACHE PATH \"Directory under which to collect all populated content\")
set (FETCHCONTENT_BASE_DIR \"/home/boris/cpp-advanced-hse/asan_build/_deps\" CACHE PATH \"Directory under which to collect all populated content\")
set (FETCHCONTENT_FULLY_DISCONNECTED OFF CACHE BOOL \"Disables all attempts to download or update content and assumes source dirs already exist\")
set (FETCHCONTENT_QUIET ON CACHE BOOL \"Enables QUIET option for all content population\")
set (FETCHCONTENT_UPDATES_DISCONNECTED OFF CACHE BOOL \"Enables UPDATE_DISCONNECTED behavior for all content population\")
set (FETCHCONTENT_UPDATES_DISCONNECTED_GLOG OFF CACHE BOOL \"Enables UPDATE_DISCONNECTED behavior just for population of Glog\")
set (FFTW_INCLUDES \"/usr/include\" CACHE PATH \"Path to a file.\")
set (FFTW_LIBRARIES \"/usr/lib/x86_64-linux-gnu/libfftw3.so\" CACHE FILEPATH \"Path to a library.\")
set (GITCOMMAND \"/usr/bin/git\" CACHE FILEPATH \"Path to a program.\")
set (GIT_EXECUTABLE \"/usr/bin/git\" CACHE FILEPATH \"Git command line client\")
set (GRADER OFF CACHE BOOL \"Building on CI\")
set (GTest_DIR \"GTest_DIR-NOTFOUND\" CACHE PATH \"The directory containing a CMake configuration file for GTest.\")
set (JPEG_INCLUDE_DIR \"/usr/include\" CACHE PATH \"Path to a file.\")
set (JPEG_LIBRARY_DEBUG \"JPEG_LIBRARY_DEBUG-NOTFOUND\" CACHE FILEPATH \"Path to a library.\")
set (JPEG_LIBRARY_RELEASE \"/usr/lib/x86_64-linux-gnu/libjpeg.so\" CACHE FILEPATH \"Path to a library.\")
set (LLVM_DIR \"/usr/lib/llvm-11/cmake\" CACHE PATH \"The directory containing a CMake configuration file for LLVM.\")
set (MAKECOMMAND \"/usr/bin/cmake --build . --config \\\"\${CTEST_CONFIGURATION_TYPE}\\\" -- -i\" CACHE STRING \"Command to build the project\")
set (MEMORYCHECK_COMMAND \"MEMORYCHECK_COMMAND-NOTFOUND\" CACHE FILEPATH \"Path to the memory checking command, used for memory error detection.\")
set (PNG_LIBRARY_DEBUG \"PNG_LIBRARY_DEBUG-NOTFOUND\" CACHE FILEPATH \"Path to a library.\")
set (PNG_LIBRARY_RELEASE \"/usr/lib/x86_64-linux-gnu/libpng.so\" CACHE FILEPATH \"Path to a library.\")
set (PNG_PNG_INCLUDE_DIR \"/usr/include\" CACHE PATH \"Path to a file.\")
set (PRINT_UNSYMBOLIZED_STACK_TRACES OFF CACHE BOOL \"Print file offsets in traces instead of symbolizing\")
set (SITE \"boris-Latitude-3410\" CACHE STRING \"Name of the computer/site where compile is being run\")
set (TEST_SOLUTION OFF CACHE BOOL \"Build solution\")
set (Unwind_INCLUDE_DIR \"Unwind_INCLUDE_DIR-NOTFOUND\" CACHE PATH \"unwind include directory\")
set (Unwind_LIBRARY \"Unwind_LIBRARY-NOTFOUND\" CACHE FILEPATH \"unwind library\")
set (Unwind_PLATFORM_LIBRARY \"Unwind_PLATFORM_LIBRARY-NOTFOUND\" CACHE FILEPATH \"unwind library platform\")
set (WITH_CUSTOM_PREFIX OFF CACHE BOOL \"Enable support for user-generated message prefixes\")
set (WITH_GMOCK ON CACHE BOOL \"Use Google Mock\")
set (WITH_GTEST ON CACHE BOOL \"Use Google Test\")
set (WITH_PKGCONFIG ON CACHE BOOL \"Enable pkg-config support\")
set (WITH_SYMBOLIZE ON CACHE BOOL \"Enable symbolize module\")
set (WITH_THREADS ON CACHE BOOL \"Enable multithreading support\")
set (WITH_TLS ON CACHE BOOL \"Enable Thread Local Storage (TLS) support\")
set (WITH_UNWIND ON CACHE BOOL \"Enable libunwind support\")
set (ZLIB_INCLUDE_DIR \"/usr/include\" CACHE PATH \"Path to a file.\")
set (ZLIB_LIBRARY_DEBUG \"ZLIB_LIBRARY_DEBUG-NOTFOUND\" CACHE FILEPATH \"Path to a library.\")
set (ZLIB_LIBRARY_RELEASE \"/usr/lib/x86_64-linux-gnu/libz.so\" CACHE FILEPATH \"Path to a library.\")
" "-P" "/home/boris/cpp-advanced-hse/asan_build/glog/glog-src/cmake/TestInitPackageConfig.cmake")
set_tests_properties(cmake_package_config_init PROPERTIES  FIXTURES_SETUP "cmake_package_config" _BACKTRACE_TRIPLES "/home/boris/cpp-advanced-hse/asan_build/glog/glog-src/CMakeLists.txt;885;add_test;/home/boris/cpp-advanced-hse/asan_build/glog/glog-src/CMakeLists.txt;0;")
add_test(cmake_package_config_generate "/usr/bin/cmake" "-DGENERATOR=Unix Makefiles" "-DGENERATOR_PLATFORM=" "-DGENERATOR_TOOLSET=" "-DINITIAL_CACHE=/home/boris/cpp-advanced-hse/asan_build/glog/glog-build/test_package_config/glog_package_config_initial_cache.cmake" "-DPACKAGE_DIR=/home/boris/cpp-advanced-hse/asan_build/glog/glog-build" "-DPATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin" "-DSOURCE_DIR=/home/boris/cpp-advanced-hse/asan_build/glog/glog-src/src/package_config_unittest/working_config" "-DTEST_BINARY_DIR=/home/boris/cpp-advanced-hse/asan_build/glog/glog-build/test_package_config/working_config" "-P" "/home/boris/cpp-advanced-hse/asan_build/glog/glog-src/cmake/TestPackageConfig.cmake")
set_tests_properties(cmake_package_config_generate PROPERTIES  FIXTURES_REQUIRED "cmake_package_config" FIXTURES_SETUP "cmake_package_config_working" _BACKTRACE_TRIPLES "/home/boris/cpp-advanced-hse/asan_build/glog/glog-src/CMakeLists.txt;892;add_test;/home/boris/cpp-advanced-hse/asan_build/glog/glog-src/CMakeLists.txt;0;")
add_test(cmake_package_config_build "/usr/bin/cmake" "--build" "/home/boris/cpp-advanced-hse/asan_build/glog/glog-build/test_package_config/working_config" "--config" "ASAN")
set_tests_properties(cmake_package_config_build PROPERTIES  FIXTURES_REQUIRED "cmake_package_config;cmake_package_config_working" _BACKTRACE_TRIPLES "/home/boris/cpp-advanced-hse/asan_build/glog/glog-src/CMakeLists.txt;904;add_test;/home/boris/cpp-advanced-hse/asan_build/glog/glog-src/CMakeLists.txt;0;")
add_test(cmake_package_config_cleanup "/usr/bin/cmake" "-E" "remove_directory" "/home/boris/cpp-advanced-hse/asan_build/glog/glog-build/test_package_config")
set_tests_properties(cmake_package_config_cleanup PROPERTIES  FIXTURES_CLEANUP "cmake_package_config" _BACKTRACE_TRIPLES "/home/boris/cpp-advanced-hse/asan_build/glog/glog-src/CMakeLists.txt;909;add_test;/home/boris/cpp-advanced-hse/asan_build/glog/glog-src/CMakeLists.txt;0;")
add_test(cleanup_init "/usr/bin/cmake" "-E" "make_directory" "/home/boris/cpp-advanced-hse/asan_build/glog/glog-build/cleanup_tests")
set_tests_properties(cleanup_init PROPERTIES  FIXTURES_SETUP "logcleanuptest" _BACKTRACE_TRIPLES "/home/boris/cpp-advanced-hse/asan_build/glog/glog-src/CMakeLists.txt;942;add_test;/home/boris/cpp-advanced-hse/asan_build/glog/glog-src/CMakeLists.txt;0;")
add_test(cleanup_logdir "/usr/bin/cmake" "-E" "remove_directory" "/home/boris/cpp-advanced-hse/asan_build/glog/glog-build/cleanup_tests")
set_tests_properties(cleanup_logdir PROPERTIES  FIXTURES_CLEANUP "logcleanuptest" _BACKTRACE_TRIPLES "/home/boris/cpp-advanced-hse/asan_build/glog/glog-src/CMakeLists.txt;944;add_test;/home/boris/cpp-advanced-hse/asan_build/glog/glog-src/CMakeLists.txt;0;")
add_test(cleanup_immediately "/usr/bin/cmake" "-DLOGCLEANUP=/home/boris/cpp-advanced-hse/asan_build/cleanup_immediately_unittest" "-DTEST_DIR=/home/boris/cpp-advanced-hse/asan_build/glog/glog-build/cleanup_tests/" "-P" "/home/boris/cpp-advanced-hse/asan_build/glog/glog-src/cmake/RunCleanerTest1.cmake")
set_tests_properties(cleanup_immediately PROPERTIES  FIXTURES_REQUIRED "logcleanuptest" WORKING_DIRECTORY "/home/boris/cpp-advanced-hse/asan_build/glog/glog-build" _BACKTRACE_TRIPLES "/home/boris/cpp-advanced-hse/asan_build/glog/glog-src/CMakeLists.txt;946;add_test;/home/boris/cpp-advanced-hse/asan_build/glog/glog-src/CMakeLists.txt;0;")
add_test(cleanup_with_prefix "/usr/bin/cmake" "-DLOGCLEANUP=/home/boris/cpp-advanced-hse/asan_build/cleanup_with_prefix_unittest" "-DTEST_DIR=/home/boris/cpp-advanced-hse/asan_build/glog/glog-build/" "-P" "/home/boris/cpp-advanced-hse/asan_build/glog/glog-src/cmake/RunCleanerTest2.cmake")
set_tests_properties(cleanup_with_prefix PROPERTIES  FIXTURES_REQUIRED "logcleanuptest" WORKING_DIRECTORY "/home/boris/cpp-advanced-hse/asan_build/glog/glog-build" _BACKTRACE_TRIPLES "/home/boris/cpp-advanced-hse/asan_build/glog/glog-src/CMakeLists.txt;953;add_test;/home/boris/cpp-advanced-hse/asan_build/glog/glog-src/CMakeLists.txt;0;")
